---
- name: "Enable and start Elasticsearch"
  register: install_elasticsearch__service_status
  changed_when: not install_elasticsearch__service_status.state != "started"
  throttle: 1
  ansible.builtin.service:
    name: "elasticsearch"
    state: "started"
    daemon_reload: true
    enabled: yes

- name: "Restart Elasticsearch"
  register: install_elasticsearch__service_status
  changed_when: not install_elasticsearch__service_status.state != "restarted"
  throttle: 1
  ansible.builtin.service:
    name: "elasticsearch"
    state: "restarted"
    daemon_reload: true
    enabled: yes