---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_elasticsearch"
      tags:
        - "labocbz.install_elasticsearch"
      vars:
        install_elasticsearch_major_version: "{{ inv_install_elasticsearch_major_version }}"
        install_elasticsearch_port: "{{ inv_install_elasticsearch_port }}"
        install_elasticsearch_cluster_name: "{{ inv_install_elasticsearch_cluster_name }}"
        install_elasticsearch_elastic_password: "{{ inv_install_elasticsearch_elastic_password }}"
        install_elasticsearch_heap: "{{ inv_install_elasticsearch_heap }}"
        install_elasticsearch_data_path: "{{ inv_install_elasticsearch_data_path }}"
        install_elasticsearch_ssl_path: "{{ inv_install_elasticsearch_ssl_path }}"
        install_elasticsearch_config_path: "{{ inv_install_elasticsearch_config_path }}"
        install_elasticsearch_client_auth: "{{ inv_install_elasticsearch_client_auth }}"
        install_elasticsearch_ssl_authorities: "{{ inv_install_elasticsearch_ssl_authorities }}"
        install_elasticsearch_ssl: "{{ inv_install_elasticsearch_ssl }}"
        install_elasticsearch_ssl_key: "{{ inv_install_elasticsearch_ssl_key }}"
        install_elasticsearch_ssl_crt: "{{ inv_install_elasticsearch_ssl_crt }}"
        install_elasticsearch_seed_hosts: "{{ inv_install_elasticsearch_seed_hosts }}"
        install_elasticsearch_initial_master_nodes: "{{ inv_install_elasticsearch_initial_master_nodes }}"
      ansible.builtin.include_role:
        name: "labocbz.install_elasticsearch"
