---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.install_elasticsearch"
      tags:
        - "labocbz.install_elasticsearch"
      vars:
        install_elasticsearch__major_version: "{{ inv_install_elasticsearch__major_version }}"
        install_elasticsearch__port: "{{ inv_install_elasticsearch__port }}"
        install_elasticsearch__cluster_name: "{{ inv_install_elasticsearch__cluster_name }}"
        install_elasticsearch__elastic_password: "{{ inv_install_elasticsearch__elastic_password }}"
        install_elasticsearch__heap: "{{ inv_install_elasticsearch__heap }}"
        install_elasticsearch__data_path: "{{ inv_install_elasticsearch__data_path }}"
        install_elasticsearch__ssl_path: "{{ inv_install_elasticsearch__ssl_path }}"
        install_elasticsearch__config_path: "{{ inv_install_elasticsearch__config_path }}"
        install_elasticsearch__client_auth: "{{ inv_install_elasticsearch__client_auth }}"
        install_elasticsearch__ssl_authorities: "{{ inv_install_elasticsearch__ssl_authorities }}"
        install_elasticsearch__ssl: "{{ inv_install_elasticsearch__ssl }}"
        install_elasticsearch__ssl_key: "{{ inv_install_elasticsearch__ssl_key }}"
        install_elasticsearch__ssl_crt: "{{ inv_install_elasticsearch__ssl_crt }}"
        install_elasticsearch__seed_hosts: "{{ inv_install_elasticsearch__seed_hosts }}"
        install_elasticsearch__initial_master_nodes: "{{ inv_install_elasticsearch__initial_master_nodes }}"
      ansible.builtin.include_role:
        name: "labocbz.install_elasticsearch"
